### ISSUE TITLE
layout picto

### ISSUE THREAD

**Issue by hanniju** [pciavald/blockfest#15]
- [x] Remove space between title & pictos.
- [x] Add space before the titles.
- [x] Increase font size for titles
- [ ] decrease font-size for subtitles
- [x] Decrease line-spacing for subtitles.
- [x] Increase the size of the pictos (but not the ones in the titles)

**Comment by pciavald** [comment]
fixed with 3d27157, see commit content for tweaking  
did not decrease font-size for subtitles, is it really necessary @hanniju ?
