### ISSUE TITLE
nouveau layout

### ISSUE THREAD

**Issue by hanniju** [pciavald/blockfest#22]
- [x] Passer les deux bandeaux "semaine" et "weekend" en une seule ligne.
- [x] Suivi de 3 boutons : Programme, inscription (peut-être un bouton qui se transforme en barre d'entrée de mail quand on clique dessus), et équipe.
- [x] En dessous, un bandeau sponsor sans scroll
- [x] et un bandeau partenaire sans scroll

![img_20160429_174835](https://cloud.githubusercontent.com/assets/5124498/14921609/5885c77c-0e33-11e6-8be7-f1a0fd6871e7.jpg)

**Comment by pciavald** [comment]
@hanniju 
- barre de nav en haut ?
- plus de fullpage au début ?
- plus de bandeau réservez ?
- plus de [tour d'horizon] / [rejoindre les contributeurs] ?
- où mènent / que font les boutons ?

**Comment by hanniju** [comment]
Précisions : 

Barre de nav en haut = plus tard
On garde le principe de fullpage
On garde un bandeau "soyez prévenu de l'ouverture des inscription", et aussi un bandeau "intervenants"

> Ordre : 
flyer 
texte
programme = semaine
weekend
intervenants
(ajout) Phrase : Le nombre de participants que nous pouvons accueillir est limité (~120 pour les conférence et ~40 pour les ateliers) est limité par les dimensions de notre équipe et du lieu qui nous accueille. Afin de garantir une bonne mixité des participations, nous vous demandons des informations sur votre statut pour garantir une bonne répartition des profils
boutons : Voire le programme (> page programme) l L'équipe du BlockFest (> Page équipe) l Bandeau : Soyez prévenus de l'ouverture des inscriptions
Partenaires

le tour d'horizon & les contributeurs passent au début de la page programme

**Comment by pciavald** [comment]
un bandeau pour sponsors et un pour partenaires ?

**Comment by pciavald** [comment]
inscription => barre mail : double usage avec bandeau soyez prévenu ?

**Comment by pciavald** [comment]
@Xalava je n'arrive pas à Passer les deux bandeaux "semaine" et "weekend" en une seule ligne, tu peux jeter un oeil ? 
https://github.com/pciavald/blockfest/blob/master/client/home/home.html#L21
