### ISSUE TITLE
programme

### ISSUE THREAD

**Issue by hanniju** [pciavald/blockfest#24]
En haut de la page, un bandeau "notre philosophie" avec :

> o Notre philosophie: ouvert, communautaire, pluridisciplinaire, festif
> o 360° + nuage (à modifier)
> o Nos outils & la documentation

*TODO soon*

![img_20160429_175737](https://cloud.githubusercontent.com/assets/5124498/14921775/3508c910-0e34-11e6-9418-1fb0d829a5ce.jpg)

**Comment by pciavald** [comment]
Réassigne-moi quand tu as fini d'écrire la description

**Comment by hanniju** [comment]
Bien, et question, est-ce que tu pense que c'est jouable pour toi de faire un template pour le programme d'ici ~mardi ?

**Comment by pciavald** [comment]
je vais essayer :)

**Comment by hanniju** [comment]
J'avance sur le mockup de cette page, voila l'état actuel
![screen shot 2016-04-30 at 17 43 40](https://cloud.githubusercontent.com/assets/5124498/14937028/225f2242-0efb-11e6-9b3b-c83ac30fe1f7.png)

**Comment by hanniju** [comment]
Sont mis à jour dans program.html : 
Les sections & titres (360, esprit & contribution)
Les pictos & sous-titres

Reste à faire:

- [ ] Placers ces 3 divs sur une même ligne (voire mockup) 
- [ ] Avancer le template de programme

Voire mockup :
![screen shot 2016-05-01 at 00 39 58](https://cloud.githubusercontent.com/assets/5124498/14938949/52fdf092-0f35-11e6-96d5-ea27309b25c8.png)

**Comment by hanniju** [comment]
New program layout
![screen shot 2016-05-02 at 00 06 28](https://cloud.githubusercontent.com/assets/5124498/14944644/c24e0044-0ff9-11e6-825f-90e153b68e1e.png)

**Comment by hanniju** [comment]
Modifs prioritaires : 
![screen shot 2016-05-02 at 01 27 47](https://cloud.githubusercontent.com/assets/5124498/14944976/2123ce9a-1005-11e6-903a-0a5ce31e0f28.png)

**Comment by hanniju** [comment]
Modifs Secondaires
![screen shot 2016-05-02 at 01 26 07](https://cloud.githubusercontent.com/assets/5124498/14944978/3775c07c-1005-11e6-97a8-b8d0b7a12b64.png)

**Comment by AlexStach** [comment]
A minima quand on sort le site, faudrait un tableau comme ca :) 

![image](https://cloud.githubusercontent.com/assets/19204592/15041379/bf1d3b28-12bb-11e6-982f-198ca85074b9.png)

**Comment by hanniju** [comment]
En image 
![screen shot 2016-05-05 at 12 21 00](https://cloud.githubusercontent.com/assets/5124498/15041396/e9c2433c-12bb-11e6-8220-1437ef12f879.png)

**Comment by pciavald** [comment]
je suis en train de le faire.

**Comment by pciavald** [comment]
je n'ai pas encore fait les hover, quelles infos dois-je mettre dedans ?
