### ISSUE TITLE
flyer covers

### ISSUE THREAD

**Issue by pciavald** [pciavald/blockfest#29]
Tester l'affichage de plusieurs image au lieu d'une seul dans le bandeau (/!\ les nouvelles image sont dans 570)

**Comment by pciavald** [comment]
@hanniju 
je n'ai pas de dossier dans 570 ni dans le drive ni sur le git, où est-il ?

**Comment by hanniju** [comment]
fixed with : https://github.com/pciavald/blockfest/commit/800f3f4dd7d991167f01bf65481d81adbb5b9fa9

**Comment by pciavald** [comment]
@hanniju plusieurs images dans quel sens ?

**Comment by pciavald** [comment]
je rouvre l'issue car bien que le dossier soit maintenant présent la feature n'est pas encore implémentée :)

**Comment by hanniju** [comment]
okay - 
Dans le sens, deux images cote-à-cote
