### ISSUE TITLE
add content for 570 covers

### ISSUE THREAD

**Issue by pciavald** [pciavald/blockfest#43]
closed #29 
add content for 570 covers
don't bother doing the meaningful naming, i have a script

**Comment by hanniju** [comment]
ok, I'll take care of it later !
In the mean time, could you block the possibility of displayong 2 time the same image ?

**Comment by pciavald** [comment]
i though i can be funny, jackpot like
i'll avoid doubles for now

**Comment by pciavald** [comment]
moved to #54
