### ISSUE TITLE
inscription => barre mail : double usage avec bandeau soyez prévenu ?

### ISSUE THREAD

**Issue by pciavald** [pciavald/blockfest#44]
ajout du bouton inscription dans #22 
y a-t-il un double usage avec le bandeau soyez prévenu ?
quel est le comportement de ces deux fonctions ?

**Comment by hanniju** [comment]
Exact, il y a double usage.

J'ai fait quelques tests en mettant la barre d'inscription au dessus des boutons programme & équipe, et en utilisant le bouton billetterie (qui deviens "soyez informés...") à la place du formulaire de mail actuel.
Si ça te conviens, 

- [ ] Il faut faire en sorte que le texte d'explication apparaisse tout le temps juste en dessous des speakers
- [ ] Il faut afficher le bouton "billetterie" ("soyez prévenus...") en dessous du texte. 
- [ ] Faire en sorte que le champ mail soit bien centré sur le bouton, et supprimer la bordure si possible (sinon on garde le champ mail actuel à la place du bouton)
- [ ] Afficher les 2 autres boutons bien centrés en dessous de tout ça
