### ISSUE TITLE
"scroll down" design

### ISSUE THREAD

**Issue by pciavald** [pciavald/blockfest#45]
display a little something after the flyer to invite the user to scroll down.
Would give more consistency to the first fullpage and the rest of the page, which is a bit confusing since the rest of the page is now the same color.

**Comment by hanniju** [comment]
I tried with a very simple picto 

- [ ] Curently,display of the arrow needs to be fixed.

Also, I think the best option might be a dynamique arrow such as : http://codepen.io/dodozhang21/pen/siKtp
> Would require to set up a delay so that it appears after the images, and maybe z-index it on top of the images
Also, we might need to move the flyer
