### ISSUE TITLE
Reglage css du logo

### ISSUE THREAD

**Issue by hanniju** [pciavald/blockfest#47]
Faire en sorte que le style (font-size / écartement lettres / weight) soient facilement éditable

**Comment by pciavald** [comment]
Pas possible de faire autrement, en tous cas je n'ai pas trouvé.
Le style est défini ici : 
https://github.com/pciavald/blockfest/blob/master/client/home/flyer.js#L73
à la ligne précédente j'applique le couple du titre du flyer au logo, puis à cette ligne je réinitialise la taille et les marges. Tu peux ajouter / modifier ces propriétés, attention elle s'appliquent de la même manière à tous les couples.
Ouvre une nouvelle issue s'il y a une mise en forme que tu n'arrives pas à faire.

**Comment by pciavald** [comment]
si cela devient nécessaire d'avoir un set de réglages css pour chaque couple je viens de penser que je peux ouvrir un nouvel objet dans la liste de couples. Plutôt pour la milestone beta à mon avis.
