### ISSUE TITLE
Home page 

### ISSUE THREAD

**Issue by hanniju** [pciavald/blockfest#52]
- [x] Add a refresh button on the flyer-image space
- [x] Take care of the scrolldown picto #45 
- [ ] Take care of the buttons #44 
- [x] Fix speakers' display bugs
- [x] Make the padding sizes in the program table look like the one at the bottom of this picture - (more compact really) 
![screen shot 2016-05-02 at 00 39 47](https://cloud.githubusercontent.com/assets/5124498/14944765/6c9abfa2-0ffe-11e6-9b6f-ea29f1e58764.png)

**Comment by pciavald** [comment]
which display bugs ?

**Comment by hanniju** [comment]
In my commits. I added 2 profils and they don't stick in line with the others :/

**Comment by pciavald** [comment]
i think you didn't push these speakers' pictures

**Comment by hanniju** [comment]
fixed in https://github.com/pciavald/blockfest/commit/c01036cece30dd3a77433610f10dd56cb0493c3f

**Comment by hanniju** [comment]
![screen shot 2016-05-02 at 10 50 13](https://cloud.githubusercontent.com/assets/5124498/14950649/bb6b95b6-1053-11e6-8ea7-a368cc5e2168.png)
