### ISSUE TITLE
Tickets page

### ISSUE THREAD

**Issue by hanniju** [pciavald/blockfest#53]
V1

\!/ Les titres ne sont pas bons, il faut utiliser par : 
Particulier - Jour
Particulier -  Semaine
Entreprise - Semaine
Blocksprint

![screen shot 2016-05-02 at 01 30 33](https://cloud.githubusercontent.com/assets/5124498/14944988/8a911266-1005-11e6-8b91-f4ff768e776f.png)

**Comment by hanniju** [comment]
V2
![screen shot 2016-05-02 at 01 30 48](https://cloud.githubusercontent.com/assets/5124498/14944991/960761fe-1005-11e6-957e-d8582541e133.png)

**Comment by hanniju** [comment]
![screen shot 2016-05-04 at 23 10 42](https://cloud.githubusercontent.com/assets/5124498/15029371/86ee6858-124d-11e6-8739-db48607c123f.png)

**Comment by hanniju** [comment]
Check for tools like http://framaforms.org/ for the form

**Comment by AlexStach** [comment]
plip plop

Faudrait une phrase descriptive des billets conf et blockparty en dessous des blocs :)

**Comment by hanniju** [comment]
Il devient prioritaire de faire de mettre en forme le tableau en prnant en compte le mockup V1 et les modif de texte tout en haut de page.
En ce qui concerne les blocs, je les préfèrerais en bas de tableau

**Comment by AlexStach** [comment]
Ploupilou,

J'approuve pour les blocs après le tableau.
