### ISSUE TITLE
[program][tickets] table border display bug

### ISSUE THREAD

**Issue by pciavald** [pciavald/blockfest#58]
there is a display bug on the right side of the tables of the pages program and tickets

![selection_010](https://cloud.githubusercontent.com/assets/3384097/15060714/eeca18ce-132d-11e6-843c-9f5786b8322a.png)
![selection_011](https://cloud.githubusercontent.com/assets/3384097/15060715/ef7758cc-132d-11e6-92d5-33e11db63b89.png)

**Comment by pciavald** [comment]
acdd9a introduced a new alignment bug between the topmost boxes
![selection_009](https://cloud.githubusercontent.com/assets/3384097/15060671/738e15e8-132d-11e6-92ae-94805543bda2.png)

**Comment by Xalava** [comment]
Aligné, ( et responsivé au passage ) #bb5df6f
Je ne vois pas les bug sur la première page
