### ISSUE TITLE
Page d'accueil - Tableaux

### ISSUE THREAD

**Issue by AlexStach** [pciavald/blockfest#68]
Plop à tous

Est ce qu'on pourrait tester le principe de "blocs" pour les éléments dela page d'accueil notamment ? Ca permet de structurer le contenu, de participer à l'identité "blocs" #blockchain 

Ca donnerait concrètement : 

le "Une semaine pour comprendre le phénomène Blockchain en profondeur en écoutant, en pratiquant, en partageant et en prototypant. 

Monté par une équipe pluri-disciplinaire passionnée par la transmission et le partage, le BlockFest a pour objectif d'être un espace-temps de construction collective, accueillant et fertile."

se retrouverait dans un même bloc (comme celui en bas pour l'inscription)

Pareil pour Programme et intervenants, faire un bloc pour chaque partie.

Si je suis incompréhensible, ce qui est fort possible, je demande l'aide de @hanniju , qui a compris ce que je voulais dire :D

**Comment by pciavald** [comment]
56e18e2 un début

**Comment by AlexStach** [comment]
Plop :) 

Great pour le premier bloc de texte. J'aurais eu tendance à mettre aussi les titres dans des blocs incluant leur contenu (genre Au programme + le tableau au dessus, mettre tout ca dans un plus gros bloc :) )

Ce serait cool aussi d'avoir un bloc autour des intervenants

**Comment by pciavald** [comment]
je pense que c'est résolu, dites moi si je me trompe.
Les intervenants ne sont actuellement pas centrés j'ai donc préféré les laisser sans bloc.
