### ISSUE TITLE
Redirection des mails

### ISSUE THREAD

**Issue by AlexStach** [pciavald/blockfest#71]
Il faudrait que contact@blockfest.fr redirige ses mails vers contact@blockchainfrance.net !

Et il faudrait me rajouter dans l'orga, me susurre @hanniju  :) 

Merciiii

**Comment by Xalava** [comment]
C'est pas lié au site, cf directement avec PA. 
Contact redirige vers nos différents mails en attendant de faire une boite dédié avec délégation
