### ISSUE TITLE
facebook image

### ISSUE THREAD

**Issue by pciavald** [pciavald/blockfest#79]
http://stackoverflow.com/questions/6693499/how-can-i-set-a-website-image-that-will-show-as-preview-on-facebook
http://stackoverflow.com/questions/16142005/how-can-i-add-xmlns-namespace-to-html-tag-in-meteor

**Comment by Xalava** [comment]
Tentative directement dans le Head 22a58b0 ( a tester)

**Comment by pciavald** [comment]
bien essayé mais ça n'a pas marché :)

**Comment by pciavald** [comment]
j'ai commencé ici
https://github.com/pciavald/blockfest/blob/master/client/body.js#L53
