### ISSUE TITLE
Modifs sur le site 

### ISSUE THREAD

**Issue by AlexStach** [pciavald/blockfest#85]
![image](https://cloud.githubusercontent.com/assets/19204592/15449003/ac8b1594-1f71-11e6-919e-ef0093b3f92e.png)
![image](https://cloud.githubusercontent.com/assets/19204592/15449004/b3e819ea-1f71-11e6-8c44-f0cde7359a88.png)

Il reste ça à changer :) + les intervenants mais je suppose qu'on verra plus tard. A minima, enlevons tout le monde sauf ceux dont on est sûrs !

**Comment by pciavald** [comment]
on mets quoi du coup ?

**Comment by AlexStach** [comment]
On enlève la première phrase. Il n'y aura qu'une cinquantaine de participants de manière générale. 

Et on enlève la partie "en semaine" puisqu'il n'y a plus de semaine :)
