### ISSUE TITLE
some fonts don't fit the flyer

### ISSUE THREAD

**Issue by pciavald** [pciavald/blockfest#9]
when the page loads on **pt-mono** font the title doesn't fit the div.

![selection_001](https://cloud.githubusercontent.com/assets/3384097/14856941/84efda36-0c9a-11e6-8d67-0aba741acbfd.png)

**Comment by pciavald** [comment]
subtitle doesn't fit with dosis

![selection_002](https://cloud.githubusercontent.com/assets/3384097/14857245/c7d4e458-0c9b-11e6-8426-c4434c2f6bfb.png)

**Comment by hanniju** [comment]
Problems fixed in the last version of my code
